### ISSUE TITLE
怎样分页加载ajax请求的数据？

### ISSUE THREAD

**Issue by holazz** [caijf/pull#1]
这个插件怎样分页加载ajax请求的数据？
```
onPullUp: function () {
    $.ajax({
        success: function(data){
            handlePullUpSuccess(data);
        },
        error: function(){
            handlePullUpFailed();
        }
    })
}
```

```
function handlePullUpSuccess(data) {
    setData(data);
    pullInstance.pullUpSuccess();
    page++;
}
```

```
function setData(data) {
    、、、
}
```
这样做为什么不行呢？

**Comment by caijf** [comment]
你的代码没问题，有完整的例子吗？

或 参考示例第二、第三例子：http://www.caijinfeng.com/temp/pull/examples/index.html

**Comment by holazz** [comment]
我这么写只加载了第一页的数据
滑到页面底部就显示这个
![image](https://user-images.githubusercontent.com/23100055/37236632-891827d0-2444-11e8-8395-0bc0b768a85a.png)
上拉也不加载了

**Comment by caijf** [comment]
看下控制台有没有报错，或 codepen提供下完整demo

**Comment by holazz** [comment]
[地址](https://codepen.io/zzjw/project/editor/ANKdbO)
地址在这里，在上面可能看不到效果，麻烦下载到本地看一下...

**Comment by caijf** [comment]
@zhangjiawei0 
已report，数据加载完成调用pullUpDone。
